### ISSUE TITLE
Consume the Sessions API by ConferenceId and Populate Existing Event List

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_android#12]
Consume the endpoint:

/api/conference/{id}/conferenceSessions

in order to populate the FullScheduleFragment with the new data.  This task includes:
- Consuming the new API
- Create new Objects that represent the JSON Payload
- Using those objects, create a view object that will be used to populate the UI
- Populate the UI with the new View Object.

**Comment by adamsova** [comment]
@jonasrob  and I are going to try and knock this out this weekend as I come up to speed.

**Comment by chenry** [comment]
Awesome. If you can hook it in to my stuff by passing in the correct eventId to the next activity, then we can consider the migration of existing g function ality pretty much completed
