### ISSUE TITLE
Build should determine the URL

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_android#15]
Part of the Build system is to allow for build specific properties.  Right now the URL for the API is hardcoded into the application.  Instead, it should be pulled from the BuildConfig.API_BASE_URL.  Use that instead of the hardcoded value.

Complexity = 1 (very easy)
Estimated effort = 15 min.
Expected completion once taken: 2 days

**Comment by KyletheWolff** [comment]
https://github.com/Google-IO-Extended-Grand-Rapids/conference_android/pull/25

**Comment by chenry** [comment]
Great job!!! @KyletheWolff
