### ISSUE TITLE
Remove all unused methods

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_android#16]
There is a lot of code that is left over from the original application that is no longer used.  Here are some key areas and places that we should remove this code:

ConferenceApplcation - couple of unused methods

Complexity = 1 (very easy)
Estimated effort = 45 min.
Expected completion once taken: 2 days

**Comment by KyletheWolff** [comment]
@chenry 
I am looking at the creation date of each file and determining from there what should be removed. Any other file in particular other than ConferenceApplcation.java?

EventData.java has a lot of methods not being used as well

Not sure which methods were created and just not used yet.

**Comment by chenry** [comment]
That is not really a good way to determine if a class should be removed or
not.  (Especially since the ConferenceApplication is at the heart of the
entire app :D).

Instead, look for warnings where methods are not being used.  Using Android
Studio, you can tell if a method is being used or not.

On Wed, Feb 25, 2015 at 12:31 PM, Kyle Wolff notifications@github.com
wrote:

> @chenry https://github.com/chenry
> I am looking at the creation date of each file and determining from there
> what should be removed. Any other file in particular other than
> ConferenceApplcation.java?
> 
> EventData.java has a lot of methods not being used as well
> 
> Not sure which methods were created and just not used yet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Google-IO-Extended-Grand-Rapids/conference_android/issues/16#issuecomment-76011964
> .

## 

Carlus Henry
SageTech L.L.C.
(616) 929-0895
www.sagetech-llc.com | http://jdcarlflip.blogspot.com/

**Comment by KyletheWolff** [comment]
@chenry I did that then I verified that the file was not made in 2015.

**Comment by chenry** [comment]
You have to look for references of the class.  That class in particular is referenced in AndroidManifest.xml

**Comment by KyletheWolff** [comment]
Do you only want me to look in that file? Or multiple such as EventData.java which has a lot of methods not being used as well
