### ISSUE TITLE
Remove the legacy heroku api service and calls

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_android#26]
This is a clean up task to remove all of the heroku api service and call references.

Please make sure that the api is not used anywhere in the application, first.  If it is, let's discuss them on a case by case basis.

**Comment by KyletheWolff** [comment]
@chenry What should we use instead of that service?

**Comment by chenry** [comment]
We are already using it.  The new api is what is pulling down the
conferences and things like that. If the other api is being used, we should
identify where it is used, and determine if we can remove it or not.

**Comment by KyletheWolff** [comment]
@chenry There is one place where this url is being used that I can find
 `public List<EventData> getEvents() {
        final RestAdapter restAdapter = new RestAdapter.Builder()
                .setEndpoint("https://conference-schedule-webap.herokuapp.com")
                .build();`

**Comment by chenry** [comment]
Okay....this may be a little trickier than I originally thought.  It is
used in one location, but that location is doing some threading and things
of that nature.  So because of that, I will have someone else look into
this issue.

Please take a peek at any of the other ones....

On Wed, Feb 25, 2015 at 12:25 PM, Kyle Wolff notifications@github.com
wrote:

> @chenry https://github.com/chenry There is one place where this url is
> being used that I can find
> public List<EventData> getEvents() {
> final RestAdapter restAdapter = new RestAdapter.Builder()
> .setEndpoint("https://conference-schedule-webap.herokuapp.com")
> .build();
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Google-IO-Extended-Grand-Rapids/conference_android/issues/26#issuecomment-76009853
> .

## 

Carlus Henry
SageTech L.L.C.
(616) 929-0895
www.sagetech-llc.com | http://jdcarlflip.blogspot.com/
