### ISSUE TITLE
Implement Conference Session Detail with new Design

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_android#31]
Use the API and return values to populate the screens.

**Comment by chenry** [comment]
@jonasrob this is the task that we spoke about today, Thursday at the office.  Thanks

**Comment by jonasrob** [comment]
@chenry all set for code review.

**Comment by chenry** [comment]
Thanks you. I will try to look at this sometime tomorrow. Happy Easter

**Comment by chenry** [comment]
Great job @jonasrob
